// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soacommmwaoiuyexmprj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvYWNvbW1td2FvaXV5ZXhtcHJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5Njk4MjUsImV4cCI6MjA2MjU0NTgyNX0.54yctaeDW-4L5YOxuTw8BwejT1yg7BYdmuw8oz7uixA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);